# Generated by Django 2.1.15 on 2020-05-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200513_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='username',
            new_name='user',
        ),
    ]
